# Generated by Django 6.0.2 on 2026-02-17 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Documentation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(blank=True, null=True, upload_to='documentation')),
                ('document_name', models.TextField(default='')),
                ('published_at', models.DateTimeField()),
            ],
        ),
    ]
