# Generated by Django 6.0.2 on 2026-02-19 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_project_alter_documentation_document_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_name',
            field=models.CharField(default='', max_length=128, unique=True),
        ),
    ]
