# Generated by Django 6.0.2 on 2026-02-19 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_project_project_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectphotos',
            name='image_description',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
