# Generated by Django 6.0.2 on 2026-02-19 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_projectphotos_image_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectphotos',
            name='image',
            field=models.ImageField(default='', upload_to='images/'),
            preserve_default=False,
        ),
    ]
