# Generated by Django 6.0.2 on 2026-02-19 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_projectphotos_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectphotos',
            name='image_name',
        ),
    ]
