# Generated by Django 6.0.2 on 2026-02-21 16:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_project_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='technologyused',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='keywords', to='home.project'),
        ),
    ]
