# Generated by Django 6.0.2 on 2026-02-21 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_technologyused_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_short_description',
            field=models.TextField(default=''),
        ),
    ]
