# Generated by Django 6.0.2 on 2026-02-22 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_project_project_short_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalPhotos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('image_description', models.TextField(blank=True, default='', null=True)),
            ],
        ),
    ]
