# Generated by Django 6.0.2 on 2026-02-22 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_personalphotos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personalphotos',
            name='image_description',
        ),
        migrations.AddField(
            model_name='personalphotos',
            name='image_name',
            field=models.TextField(default='', unique=True),
        ),
    ]
