# Generated by Django 6.0.2 on 2026-03-24 20:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Grant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, choices=[('AI', 'Ai'), ('in', 'In'), ('Manufacturing', 'Manufacturing')])),
                ('status', models.CharField(blank=True, choices=[('Application', 'Application'), ('in', 'In'), ('Progress', 'Progress')])),
                ('grant_name', models.TextField()),
                ('grant_url', models.URLField()),
                ('found_date', models.DateTimeField()),
                ('due_date', models.DateTimeField()),
                ('slug', models.SlugField(blank=True, max_length=128, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='GrantActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update_text', models.TextField()),
                ('timestamp', models.DateTimeField()),
                ('grant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grant_tracker.grant')),
            ],
        ),
        migrations.CreateModel(
            name='GrantDocuments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(upload_to='documents/')),
                ('document_description', models.TextField(blank=True, default='', null=True)),
                ('grant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grant_tracker.grant')),
            ],
        ),
    ]
